module.exports = class Constants {

    static ECONOMY_SEARCH_LIST = [
        "You found <amount> coins in the air, how the...?",
        "You looked up in the air, and found nothing.",
        "You found <amount> coins in Area 51, NOW RUN THE GOVERNMENT IS COMING",
        "You approach Area 51 and instantly get shot by the government.",
        "You found <amount> coins in the attic, I wonder who left that up there",
        "You died from eating insulation in the attic.",
        "You found <amount> coins from a bank, DID YOU JUST ROB THAT BANK",
        "While searching at the bank, someone robbed the place and didn't like the funny look you gave them. You got shot and died.",
        "You found <amount> coins, in your basement",
        "You found <amount> coins in your bed.",
        "You couldn't find any spare coins in your bed.",
        "You found <amount> coins on the bus, but its covered in old gum...",
        "You found <amount> coins in some bushes, luckily you didn't get pricked",
        "So excited to find some coins, you dove right into a prickly bush and died. Congrats.",
        "You found <amount> coins from in someones car, thank god for this idiot for leaving their car unlocked",
        "You got hit by a car LOL. Next time lets NOT jump in front of traffic for a few coins...",
        "You found <amount> coins in an old coat, wonder how long that's been there!",
        "You found <amount> coins in your couch, I wonder how long you've been sitting on this?",
        "You forgot you stored your peanut butter in the couch cushions, you're allergic and you died idiot",
        "You searched through your dms and found <amount> coins",
        "You got catfished on Discord, and uh, disappeared.",
        "You found <amount> coins, that poor poor dog...",
        "The dog wasn't done with that, and bit you.",
        "You found <amount> coins in your dresser!",
        "You found <amount> coins in a dumpser!",
        "You couldn't find any coins while searching a dumpster.",
        "You found <amount> coins in your fridge!",
        "You couldn't find any coins while searching your fridge.",
        "You found <amount> coins in your garage!",
        "You searched the grass and found <amount> coins!",
        "You found <amount> coins at a hospital, did you steal this from a sick person???",
        "You walked into the infectious disease ward and contracted something deadly.",
        "You found <amount> coins on the kitchen counter top, nobody knows who it belongs to, so now it's yours! you can buy a snack now!",
        "The cold, lonely, barely lit empty test kitchen sent chills down your spine and you ran away! Scary...",
        "You found <amount> coins in your mailbox, cool?",
        "You found <amount> coins in your pocket, now it's in your wallet.	",
        "You stole <amount> coins from an old ladies purse, now this poor old lady can't get her medicine. Are you proud?",
        "The old lady did NOT appreciate you searching her purse, and hit you with her purse... TO DEATH.",
        "You found <amount> coins in the sewers, why the heck is this down here",
        "You found <amount> coins in your shoe, why was this in your shoe?",
        "You found <amount> coins in your dirty nasty sink, do your dishes!",
    ]
}